# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils import imgstream_pb2 as imgstream__pb2


class ImgStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.stream = channel.unary_unary(
                '/ImgStream/stream',
                request_serializer=imgstream__pb2.Req.SerializeToString,
                response_deserializer=imgstream__pb2.Res.FromString,
                )


class ImgStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImgStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'stream': grpc.unary_unary_rpc_method_handler(
                    servicer.stream,
                    request_deserializer=imgstream__pb2.Req.FromString,
                    response_serializer=imgstream__pb2.Res.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImgStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImgStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImgStream/stream',
            imgstream__pb2.Req.SerializeToString,
            imgstream__pb2.Res.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
